# 定義の詳細は下記参照
# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # 監視するパッケージマネージャーを指定する。
  - package-ecosystem: "pub"

    # パッケージマニフェストの場所を指定する。
    directory: "/"

    # 確認頻度を指定する。
    schedule:
      interval: "weekly"
