# Copyright 2022 susatthi All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    constant_identifier_names: true
    prefer_relative_imports: true

# see: https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/localizations/*.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/riverpod_graph.dart'
    - '**/utils/assets/*.gen.dart'
  errors:
    invalid_annotation_target: ignore
