# Copyright 2022 susatthi All rights reserved.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

name: github_search
description: GitHub API を利用して GitHub のリポジトリを検索するアプリです。株式会社ゆめみのFlutterエンジニアコードチェックの要件を満たすよう実装しています。
publish_to: 'none'
version: 0.9.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  collection:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_riverpod: ^2.4.3
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^11.1.3
  hexcolor: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  intl:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  markdown: ^7.1.1
  number_display: ^3.0.0
  path_provider:
  photo_view: ^0.14.0
  responsive_framework: ^0.2.0
  roggle: ^0.3.2
  shimmer: ^3.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.14
  visibility_detector:

dev_dependencies:
  build_runner:
  fast_i18n: ^5.12.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.3
  golden_toolkit: ^0.15.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  path: ^1.8.3
  pedantic_mono: ^1.24.0
  sqflite_common_ffi: ^2.3.0+2

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/fonts/Murecho/static/Murecho-Thin.ttf
          weight: 100
        - asset: assets/fonts/Murecho/static/Murecho-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Murecho/static/Murecho-Light.ttf
          weight: 300
        - asset: assets/fonts/Murecho/static/Murecho-Regular.ttf
          weight: 400
        - asset: assets/fonts/Murecho/static/Murecho-Medium.ttf
          weight: 500
        - asset: assets/fonts/Murecho/static/Murecho-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Murecho/static/Murecho-Bold.ttf
          weight: 700
        - asset: assets/fonts/Murecho/static/Murecho-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Murecho/static/Murecho-Black.ttf
          weight: 900
  uses-material-design: true

flutter_gen:
  output: lib/util/assets/
